export const GET_FASHION_LOAD = "GET_FASHION_LOAD";
export const GET_FASHION_SUCCESS = "GET_FASHION_SUCCESS";
export const GET_FASHION_FAIL = "GET_FASHION_FAIL";

export const GET_FASHIONCATEGORY_LOAD = "GET_FASHIONCATEGORY_LOAD";
export const GET_FASHIONCATEGORY_SUCCESS = "GET_FASHIONCATEGORY_SUCCESS";
export const GET_FASHIONCATEGORY_FAIL = "GET_FASHIONCATEGORY_FAIL";

export const GET_FASHIONCATEGORYSUBCATEGORY_LOAD = "GET_FASHIONCATEGORYSUBCATEGORY_LOAD";
  export const GET_FASHIONCATEGORYSUBCATEGORY_SUCCESS =
    "GET_FASHIONCATEGORYSUBCATEGORY_SUCCESS";
  export const GET_FASHIONCATEGORYSUBCATEGORY_FAIL =
    "GET_FASHIONCATEGORYSUBCATEGORY_FAIL";

    export const ADD_FASHION_LOAD = "ADD_FASHION_LOAD";
    export const ADD_FASHION_SUCCESS = "ADD_FASHION_SUCCESS";
    export const ADD_FASHION_FAIL = "ADD_FASHION_FAIL";

    export const GET_FASHION_BYID_LOAD = "GET_FASHION_BYID_LOAD";
    export const GET_FASHION_BYID_SUCCESS = "GET_FASHION_BYID_SUCCESS";
    export const GET_FASHION_BYID_FAIL = "GET_FASHION_BYID_FAIL";
    
    export const DELETE_FASHION_BYID_LOAD = "DELETE_FASHION_BYID_LOAD";
    export const DELETE_FASHION_BYID_SUCCESS = "DELETE_FASHION_BYID_SUCCESS";
    export const DELETE_FASHION_BYID_FAIL = "DELETE_FASHION_BYID_FAIL";

    export const EDIT_FASHION_LOAD = "EDIT_FASHION_LOAD";
    export const EDIT_FASHION_SUCCESS = "EDIT_FASHION_SUCCESS";
    export const EDIT_FASHION_FAIL = "EDIT_FASHION_FAIL";