export const GET_HOMEGARDEN_LOAD = "GET_HOMEGARDEN_LOAD";
export const GET_HOMEGARDEN_SUCCESS = "GET_HOMEGARDEN_SUCCESS";
export const GET_HOMEGARDEN_FAIL = "GET_HOMEGARDEN_FAIL";

export const GET_HOMEGARDENCATEGORY_LOAD = "GET_HOMEGARDENCATEGORY_LOAD";
export const GET_HOMEGARDENCATEGORY_SUCCESS = "GET_HOMEGARDENCATEGORY_SUCCESS";
export const GET_HOMEGARDENCATEGORY_FAIL = "GET_HOMEGARDENCATEGORY_FAIL";

export const ADD_HOMEGARDEN_LOAD = "ADD_HOMEGARDEN_LOAD";
export const ADD_HOMEGARDEN_SUCCESS = "ADD_HOMEGARDEN_SUCCESS";
export const ADD_HOMEGARDEN_FAIL = "ADD_HOMEGARDEN_FAIL";

export const GET_HOMEGARDEN_BYID_LOAD = "GET_HOMEGARDEN_BYID_LOAD";
export const GET_HOMEGARDEN_BYID_SUCCESS = "GET_HOMEGARDEN_BYID_SUCCESS";
export const GET_HOMEGARDEN_BYID_FAIL = "GET_HOMEGARDEN_BYID_FAIL";

export const DELETE_HOMEGARDEN_BYID_LOAD = "DELETE_HOMEGARDEN_BYID_LOAD";
export const DELETE_HOMEGARDEN_BYID_SUCCESS = "DELETE_HOMEGARDEN_BYID_SUCCESS";
export const DELETE_HOMEGARDEN_BYID_FAIL = "DELETE_HOMEGARDEN_BYID_FAIL";

export const EDIT_HOMEGARDEN_LOAD = "EDIT_HOMEGARDEN_LOAD";
export const EDIT_HOMEGARDEN_SUCCESS = "EDIT_HOMEGARDEN_SUCCESS";
export const EDIT_HOMEGARDEN_FAIL = "EDIT_HOMEGARDEN_FAIL";