export const GET_REALESTATE_LOAD = "GET_REALESTATE_LOAD";
export const GET_REALESTATE_SUCCESS = "GET_REALESTATE_SUCCESS";
export const GET_REALESTATE_FAIL = "GET_REALESTATE_FAIL";

export const GET_REALESTATECATEGORY_LOAD = "GET_REALESTATECATEGORY_LOAD";
export const GET_REALESTATECATEGORY_SUCCESS = "GET_REALESTATECATEGORY_SUCCESS";
export const GET_REALESTATECATEGORY_FAIL = "GET_REALESTATECATEGORY_FAIL";

export const ADD_REALESTATE_LOAD = "ADD_REALESTATE_LOAD";
export const ADD_REALESTATE_SUCCESS = "ADD_REALESTATE_SUCCESS";
export const ADD_REALESTATE_FAIL = "ADD_REALESTATE_FAIL";

export const GET_REALESTATE_BYID_LOAD = "GET_REALESTATE_BYID_LOAD";
export const GET_REALESTATE_BYID_SUCCESS = "GET_REALESTATE_BYID_SUCCESS";
export const GET_REALESTATE_BYID_FAIL = "GET_REALESTATE_BYID_FAIL";

export const DELETE_REALESTATE_BYID_LOAD = "DELETE_REALESTATE_BYID_LOAD";
export const DELETE_REALESTATE_BYID_SUCCESS = "DELETE_REALESTATE_BYID_SUCCESS";
export const DELETE_REALESTATE_BYID_FAIL = "DELETE_REALESTATE_BYID_FAIL";

export const EDIT_REALESTATE_LOAD = "EDIT_REALESTATE_LOAD";
export const EDIT_REALESTATE_SUCCESS = "EDIT_REALESTATE_SUCCESS";
export const EDIT_REALESTATE_FAIL = "EDIT_REALESTATE_FAIL";