export const GET_VACATION_LOAD = "GET_VACATION_LOAD";
export const GET_VACATION_SUCCESS = "GET_VACATION_SUCCESS";
export const GET_VACATION_FAIL = "GET_VACATION_FAIL";

export const GET_VACATIONCATEGORY_LOAD = "GET_VACATIONCATEGORY_LOAD";
export const GET_VACATIONCATEGORY_SUCCESS = "GET_VACATIONCATEGORY_SUCCESS";
export const GET_VACATIONCATEGORY_FAIL = "GET_VACATIONCATEGORY_FAIL";

export const ADD_VACATION_LOAD = "ADD_VACATION_LOAD";
export const ADD_VACATION_SUCCESS = "ADD_VACATION_SUCCESS";
export const ADD_VACATION_FAIL = "ADD_VACATION_FAIL";

export const GET_VACATION_BYID_LOAD = "GET_VACATION_BYID_LOAD";
export const GET_VACATION_BYID_SUCCESS = "GET_VACATION_BYID_SUCCESS";
export const GET_VACATION_BYID_FAIL = "GET_VACATION_BYID_FAIL";

export const DELETE_VACATION_BYID_LOAD = "DELETE_VACATION_BYID_LOAD";
export const DELETE_VACATION_BYID_SUCCESS = "DELETE_VACATION_BYID_SUCCESS";
export const DELETE_VACATION_BYID_FAIL = "DELETE_VACATION_BYID_FAIL";

export const EDIT_VACATION_LOAD = "EDIT_VACATION_LOAD";
export const EDIT_VACATION_SUCCESS = "EDIT_VACATION_SUCCESS";
export const EDIT_VACATION_FAIL = "EDIT_VACATION_FAIL";