export const GET_VEHICLES_LOAD = "GET_VEHICLES_LOAD";
export const GET_VEHICLES_SUCCESS = "GET_VEHICLES_SUCCESS";
export const GET_VEHICLES_FAIL = "GET_VEHICLES_FAIL";

export const GET_VEHICLESCATEGORYSUBCATEGORY_LOAD =
  "GET_VEHICLESCATEGORYSUBCATEGORY_LOAD";
export const GET_VEHICLESCATEGORYSUBCATEGORY_SUCCESS =
  "GET_VEHICLESCATEGORYSUBCATEGORY_SUCCESS";
export const GET_VEHICLESCATEGORYSUBCATEGORY_FAIL =
  "GET_VEHICLESCATEGORYSUBCATEGORY_FAIL";

  export const GET_VEHICLESCATEGORY_LOAD = "GET_VEHICLESCATEGORY_LOAD";
  export const GET_VEHICLESCATEGORY_SUCCESS = "GET_VEHICLESCATEGORY_SUCCESS";
  export const GET_VEHICLESCATEGORY_FAIL = "GET_VEHICLESCATEGORY_FAIL";
  
  export const ADD_VEHICLES_LOAD = "ADD_VEHICLES_LOAD";
  export const ADD_VEHICLES_SUCCESS = "ADD_VEHICLES_SUCCESS";
  export const ADD_VEHICLES_FAIL = "ADD_VEHICLES_FAIL";

  export const GET_VEHICLE_BYID_LOAD = "GET_VEHICLE_BYID_LOAD";
  export const GET_VEHICLE_BYID_SUCCESS = "GET_VEHICLE_BYID_SUCCESS";
  export const GET_VEHICLE_BYID_FAIL = "GET_VEHICLE_BYID_FAIL";

   export const DELETE_VEHICLES_BYID_LOAD = "DELETE_VEHICLES_BYID_LOAD";
   export const DELETE_VEHICLES_BYID_SUCCESS = "DELETE_VEHICLES_BYID_SUCCESS";
   export const DELETE_VEHICLES_BYID_FAIL = "DELETE_VEHICLES_BYID_FAIL";
  
     export const EDIT_VEHICLES_LOAD = "EDIT_VEHICLESCATEGORY_LOAD";
     export const EDIT_VEHICLES_SUCCESS = "EDIT_VEHICLESCATEGORY_SUCCESS";
     export const EDIT_VEHICLES_FAIL = "EDIT_VEHICLESCATEGORY_FAIL";